### PR TITLE
nav-bar

### PR DESCRIPTION
**Pull request by nikhilhvr**

### CODE REVIEW

**Review by Abhishekvrt — CHANGES_REQUESTED** [review]
@nikhilhvr write in comments why you commented this routing function so everybody can know "What is the problem here??"

**Comment by Abhishekvrt** [comment]
@nikhilhvr Why you deleted Navbar.js?? 🤔

**Comment by nikhilhvr** [comment]
> @nikhilhvr Why you deleted Navbar.js?? 🤔



> 
> 
> @nikhilhvr write in comments why you commented this routing function so everybody can know "What is the problem here??"

@Abhishekvrt Routing is not working for me and @MardavJadaun has the same issue with routing. The seems to be blank for us So,comment out this routing code.

**Review by Abhishekvrt — APPROVED** [review]
Badhiya bhaiii

**Pull request merged**
